#!/bin/bash
#
# A script to update a linux distro based on Arch, OpenSUSE, Fedora or Debian.
# Version: 0.1
# Copyright (C) 2024 Ronald Jørnsøn
# 45grn6meov@runbox.email
#
# SPDX-License_Identifier: GPL-3.0-or-later
#
# https://www.gnu.org/licenses/gpl-3.0-standalone.html

#set -e

release_file=/etc/os-release
errorlog=/var/log/updater_errors.log

check_exit_status() {
  if [ $? -ne 0 ]; then
    echo "An error occured. Check the $errorlog file."
  fi
}

if grep -q "debian" $release_file ; then
  # the host is based on Debian, run the apt update command.
  sudo apt-get update 2>>$errorlog
  check_exit_status

  sudo apt-get dist-upgrade -y 2>>$errorlog
  check_exit_status
fi

if grep -q "Arch" $release_file ; then
  # the host is based on arch, run the pacman update command.
  sudo pacman -Syu 2>>$errorlog
  check_exit_status
fi

if grep -q "Fedora" $release_file ; then
  # the host is based on Fedora, run the dnf upgrade command
  sudo dnf upgrade 2>>$errorlog
  check_exit_status
fi

if grep -q "opensuse-tumbleweed" $release_file ; then
  # the host is based on OpenSUSE Tumbleweed, run the zypper command
  sudo zypper dup 2>>$errorlog
  check_exit_status
fi

if grep -q "opensuse-leap" $release_file ; then
  # the host is based on OpenSUSE Leap, run the zypper command
  sudo zypper up 2>>$errorlog
  check_exit_status
fi

exit
